In [3]:
import numpy as np

In [4]:
v=np.array([11,22,33,44,55])

In [5]:
v

array([11, 22, 33, 44, 55])

In [6]:
v.ndim#dimensions

1

In [7]:
#2d array
vv=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [8]:
vv

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [9]:
print(vv)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [10]:
v.ndim  #same as print(a.ndim)

1

In [11]:
vv.shape

(2, 5)

In [16]:
vv.size

10

In [17]:
v.size

5

In [19]:
v.itemsize  

4

In [21]:
f=np.array([1,2,3],dtype="float64")

In [22]:
f

array([1., 2., 3.])

In [23]:
f.itemsize

8

In [26]:
vv[0,2]

3

In [34]:
vv[0:3]


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [35]:
vv[:,4]

array([ 5, 10])

In [36]:
vv[:2,2:]

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [37]:
vv[:4,4:]

array([[ 5],
       [10]])

In [40]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [44]:
np.ones((1,1),dtype="int32")

array([[1]])

In [45]:
vv.dtype

dtype('int32')

In [46]:
np.full((4,4),66)

array([[66, 66, 66, 66],
       [66, 66, 66, 66],
       [66, 66, 66, 66],
       [66, 66, 66, 66]])

In [47]:
np.full_like(f,4) #like f array it will create matrix i,e array

array([4., 4., 4.])

In [48]:
np.random.rand(3,3)  #default it will take values between 0 and 1

array([[0.62472004, 0.32388831, 0.54244649],
       [0.44060937, 0.65660009, 0.60124532],
       [0.56350974, 0.26016884, 0.21806725]])

In [51]:
np.random.randint(5,10,size=(3,3))

array([[5, 7, 7],
       [8, 8, 6],
       [9, 7, 6]])

In [54]:
np.identity(6,dtype="int32")

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

In [55]:
vv+20

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [56]:
vv+v

array([[12, 24, 36, 48, 60],
       [17, 29, 41, 53, 65]])

In [57]:
vv**3

array([[   1,    8,   27,   64,  125],
       [ 216,  343,  512,  729, 1000]], dtype=int32)

In [58]:
np.sin(v)

array([-0.99999021, -0.00885131,  0.99991186,  0.01770193, -0.99975517])

In [59]:
np.cos(v)

array([ 0.0044257 , -0.99996083, -0.01327675,  0.99984331,  0.02212676])

In [62]:
np.tan(v)

array([-2.25950846e+02,  8.85165604e-03, -7.53130148e+01,  1.77046993e-02,
       -4.51830879e+01])

In [67]:
a=np.array([1,2])

In [68]:
b=np.array([3,4])

In [69]:
np.matmul(a,b)

11

more functions

In [13]:
type(v)

numpy.ndarray

In [14]:
v.dtype

dtype('int32')

In [15]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [29]:
np.linspace(0,2,100)# functions having lots of _

array([0.        , 0.02020202, 0.04040404, 0.06060606, 0.08080808,
       0.1010101 , 0.12121212, 0.14141414, 0.16161616, 0.18181818,
       0.2020202 , 0.22222222, 0.24242424, 0.26262626, 0.28282828,
       0.3030303 , 0.32323232, 0.34343434, 0.36363636, 0.38383838,
       0.4040404 , 0.42424242, 0.44444444, 0.46464646, 0.48484848,
       0.50505051, 0.52525253, 0.54545455, 0.56565657, 0.58585859,
       0.60606061, 0.62626263, 0.64646465, 0.66666667, 0.68686869,
       0.70707071, 0.72727273, 0.74747475, 0.76767677, 0.78787879,
       0.80808081, 0.82828283, 0.84848485, 0.86868687, 0.88888889,
       0.90909091, 0.92929293, 0.94949495, 0.96969697, 0.98989899,
       1.01010101, 1.03030303, 1.05050505, 1.07070707, 1.09090909,
       1.11111111, 1.13131313, 1.15151515, 1.17171717, 1.19191919,
       1.21212121, 1.23232323, 1.25252525, 1.27272727, 1.29292929,
       1.31313131, 1.33333333, 1.35353535, 1.37373737, 1.39393939,
       1.41414141, 1.43434343, 1.45454545, 1.47474747, 1.49494

In [30]:
b=np.arange(6)

In [31]:
b

array([0, 1, 2, 3, 4, 5])

In [32]:
c=np.arange(12).reshape(4,3)

In [33]:
c

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [34]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [35]:
b<5

array([ True,  True,  True,  True,  True, False])

In [40]:
b*=3

In [41]:
b

array([ 0,  3,  6,  9, 12, 15])

In [42]:
import math

In [43]:
print(math.pi)

3.141592653589793


In [45]:
d=np.linspace(0,math.pi,3)

In [46]:
d

array([0.        , 1.57079633, 3.14159265])

In [47]:
e=np.exp(c*1j)

In [48]:
e

array([[ 1.        +0.j        ,  0.54030231+0.84147098j,
        -0.41614684+0.90929743j],
       [-0.9899925 +0.14112001j, -0.65364362-0.7568025j ,
         0.28366219-0.95892427j],
       [ 0.96017029-0.2794155j ,  0.75390225+0.6569866j ,
        -0.14550003+0.98935825j],
       [-0.91113026+0.41211849j, -0.83907153-0.54402111j,
         0.0044257 -0.99999021j]])

In [50]:
b.sum()

45

In [51]:
e.max()

(1+0j)

In [52]:
e.min()

(-0.9899924966004454+0.1411200080598672j)

In [53]:
c.sum(axis=0)

array([18, 22, 26])

In [54]:
c.cumsum(axis=1)#cumulative sum along each row

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21],
       [ 9, 19, 30]], dtype=int32)

In [55]:
for element in b.flat:
    print(element)

0
3
6
9
12
15


In [56]:
for row in b:
    print(row)

0
3
6
9
12
15


In [57]:
a=np.floor(10*np.random.random((3,4)))

In [58]:
a

array([[1., 1., 1., 5.],
       [6., 2., 1., 9.],
       [5., 5., 9., 3.]])

In [59]:
a.shape

(3, 4)

In [60]:
a.ravel()#returns array flattened

array([1., 1., 1., 5., 6., 2., 1., 9., 5., 5., 9., 3.])

In [62]:
a.T#transposed

array([[1., 6., 5.],
       [1., 2., 5.],
       [1., 1., 9.],
       [5., 9., 3.]])

In [63]:
a.T.shape

(4, 3)

In [65]:
a=np.floor(10*np.random.random((2,2)))

In [68]:
b=np.floor(10*np.random.random((2,2)))

In [69]:
np.vstack((a,b))

array([[6., 7.],
       [4., 7.],
       [6., 6.],
       [1., 3.]])

In [70]:
np.hstack((a,b))

array([[6., 7., 6., 6.],
       [4., 7., 1., 3.]])

In [71]:
np.column_stack((a,b))

array([[6., 7., 6., 6.],
       [4., 7., 1., 3.]])

In [73]:
from numpy import newaxis

In [74]:
a[:,newaxis]

array([[[6., 7.]],

       [[4., 7.]]])

In [75]:
np.r_[1:4,0,4]

array([1, 2, 3, 0, 4])

In [78]:
e=np.floor(10*np.random.random((2,12)))

In [80]:
np.hsplit(a,2)

[array([[6.],
        [4.]]),
 array([[7.],
        [7.]])]

In [81]:
np.hsplit(a,(3,4))

[array([[6., 7.],
        [4., 7.]]),
 array([], shape=(2, 0), dtype=float64),
 array([], shape=(2, 0), dtype=float64)]

In [82]:
b is a

False

In [84]:
id(a)#unique identification for object

2347870651952

In [87]:
c=a.view()

In [88]:
c

array([[6., 7.],
       [4., 7.]])

In [89]:
a

array([[6., 7.],
       [4., 7.]])

In [90]:
c is a

False

In [91]:
c.base is a

True

In [92]:
c.flags.owndata

False

In [93]:
s=a[:,1:3]

In [95]:
s[:]#same as s

array([[7.],
       [7.]])

In [96]:
a

array([[6., 7.],
       [4., 7.]])

In [97]:
#deep cpy
d=a.copy()

In [98]:
d

array([[6., 7.],
       [4., 7.]])

In [99]:
a

array([[6., 7.],
       [4., 7.]])

In [100]:
 d is a

False

In [101]:
d.base is a

False

In [102]:
d[0,0]=9999

In [103]:
d

array([[9.999e+03, 7.000e+00],
       [4.000e+00, 7.000e+00]])

In [108]:
del a#memory of d is released

In [109]:
h=np.array([1,1,2,3,4,5.5,4,3])

In [110]:
np.unique(h)

array([1. , 2. , 3. , 4. , 5.5])

In [112]:
np.unique(h,return_counts=True)

(array([1. , 2. , 3. , 4. , 5.5]), array([2, 1, 2, 2, 1], dtype=int64))

In [113]:
aa=np.random.randint(10,size=(4,3))

In [114]:
aa

array([[6, 5, 7],
       [1, 0, 6],
       [0, 4, 8],
       [6, 6, 6]])

In [115]:
np.argmax(aa,axis=1)

array([2, 2, 2, 0], dtype=int64)

In [117]:
np.argmin(aa,axis=0)

array([2, 1, 1], dtype=int64)

In [118]:
hh=np.random.rand(1000)

In [119]:
print(hh.mean())

0.49266875193934434


In [120]:
print(hh.var())

0.083283598162589


In [121]:
np.random.shuffle(aa)

In [122]:
aa

array([[1, 0, 6],
       [6, 6, 6],
       [6, 5, 7],
       [0, 4, 8]])

In [124]:
np.expand_dims(aa,axis=0).ndim

3

In [125]:
np.count_nonzero(aa)

10

In [126]:
np.argwhere(aa)

array([[0, 0],
       [0, 2],
       [1, 0],
       [1, 1],
       [1, 2],
       [2, 0],
       [2, 1],
       [2, 2],
       [3, 1],
       [3, 2]], dtype=int64)

In [127]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [129]:
np.vsplit(aa,2)[0]

array([[1, 0, 6],
       [6, 6, 6]])

In [130]:
np.abs(aa)

array([[1, 0, 6],
       [6, 6, 6],
       [6, 5, 7],
       [0, 4, 8]])

In [132]:
np.around(aa,2)

array([[1, 0, 6],
       [6, 6, 6],
       [6, 5, 7],
       [0, 4, 8]])

In [134]:
np.round(aa,2)

array([[1, 0, 6],
       [6, 6, 6],
       [6, 5, 7],
       [0, 4, 8]])